#!/usr/bin/env bash
set -euo pipefail

# Generates git-loopy.env — a sourceable file that exports the pinned Copilot
# defaults and defines one shell function per skill wrapper.
#
# Nothing outside this repository is read or written: no rc files, no $HOME.
# The generated file is git-ignored, so it belongs to your working copy alone.
#
#   scripts/generate-shell-env.sh   # write ./git-loopy.env
#   source git-loopy.env            # load the wrappers into the current shell
#   wayfinder <loose idea>
#
# Options:
#   --out PATH   write somewhere else; "-" means stdout
#   --print      write to stdout (same as --out -)
#   --force      overwrite a file this script did not generate
#   -h, --help   show this help

SKILLS=(wayfinder to-spec to-tickets)
STAMP="# GENERATED by scripts/generate-shell-env.sh — do not edit; regenerate instead."

REPO="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$REPO/git-loopy.env"
FORCE=0

usage() { sed -n '4,21p' "$0" | sed 's/^# \{0,1\}//'; }

while [ $# -gt 0 ]; do
  case "$1" in
    --out) OUT="${2:?--out needs a path}"; shift 2 ;;
    --print) OUT="-"; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) printf 'unknown option: %s\n\n' "$1" >&2; usage >&2; exit 2 ;;
  esac
done

generate() {
  cat <<EOF
# git-loopy.env — source this to get the skill wrappers in your shell.
#
$STAMP
# Git-ignored: it belongs to your working copy, not to the repository.
#
#   source git-loopy.env
#
# Each wrapper opens a session on one skill with model, effort and context pinned
# as flags, because flags outrank every other layer (agent frontmatter,
# .github/copilot/settings.json, ~/.copilot/settings.json) and contextTier cannot
# be expressed in an .agent.md at all.
#
# -i, not -p: these sessions are human-in-the-loop, so the session has to stay
# live. -p would exit after the first turn and the agent would grill an empty room.

# Pre-set any of these before sourcing and your value wins.
export GIT_LOOPY_MODEL="\${GIT_LOOPY_MODEL:-claude-opus-5}"
export GIT_LOOPY_EFFORT="\${GIT_LOOPY_EFFORT:-xhigh}"
export GIT_LOOPY_CONTEXT="\${GIT_LOOPY_CONTEXT:-long_context}"

# GIT_LOOPY_CLI is resolved per call rather than exported: \`co\` is a shell
# function in some setups, so a value captured here would not survive into a
# shell that has no such function.
_git_loopy_cli() {
    if [ -n "\${GIT_LOOPY_CLI:-}" ]; then
        printf '%s\n' "\$GIT_LOOPY_CLI"
    elif command -v co >/dev/null 2>&1; then
        printf 'co\n'
    else
        printf 'copilot\n'
    fi
}

_git_loopy_skill() {
    local skill="\$1"
    shift

    local prompt="/\$skill"
    [ "\$#" -gt 0 ] && prompt="\$prompt \$*"

    local cli
    cli="\$(_git_loopy_cli)"
    if ! command -v "\$cli" >/dev/null 2>&1; then
        printf 'git-loopy: %s not found on PATH — install the GitHub Copilot CLI\n' "\$cli" >&2
        return 127
    fi

    "\$cli" \\
        --agent "\$skill" \\
        --model "\${GIT_LOOPY_MODEL:-claude-opus-5}" \\
        --effort "\${GIT_LOOPY_EFFORT:-xhigh}" \\
        --context "\${GIT_LOOPY_CONTEXT:-long_context}" \\
        -i "\$prompt"
}
EOF

  local skill
  for skill in "${SKILLS[@]}"; do
    printf '\n'
    case "$skill" in
      wayfinder)
        printf '#   wayfinder <loose idea>        # chart a new map\n'
        printf '#   wayfinder <map> [ticket]      # work through an existing map\n'
        ;;
      to-spec)
        printf '#   to-spec                       # synthesize this conversation into a spec\n'
        ;;
      to-tickets)
        printf '#   to-tickets [spec]             # slice a spec into tracer-bullet tickets\n'
        ;;
      *)
        printf '#   %s [args]\n' "$skill"
        ;;
    esac
    printf '%s() { _git_loopy_skill %s "$@"; }\n' "$skill" "$skill"
  done
}

if [ "$OUT" = "-" ]; then
  generate
  exit 0
fi

# The file is generated and disposable, but a hand-written one at the same path is
# not — refuse to clobber anything this script did not write.
if [ -e "$OUT" ] && [ "$FORCE" -eq 0 ] && ! grep -qF "$STAMP" "$OUT"; then
  printf 'refusing to overwrite %s: not generated by this script (use --force)\n' "$OUT" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"
tmp="$(mktemp "${TMPDIR:-/tmp}/git-loopy-env.XXXXXX")"
generate >"$tmp"
mv "$tmp" "$OUT"

rel="$OUT"
case "$rel" in "$REPO"/*) rel="${rel#"$REPO"/}" ;; esac
printf 'wrote %s — load it with:  source %s\n' "$rel" "$rel"
printf 'wrappers: %s\n' "${SKILLS[*]}"
